"""匯出所有 Pydantic Schema"""

from app.schemas.admin import (
    AdminUserCreate,
    AdminUserListResponse,
    AdminUserResponse,
    AdminUserUpdate,
    AuditLogListResponse,
    AuditLogResponse,
    CreateUserRequest,
    SystemHealthResponse,
    ToggleActiveResponse,
    UpdateUserRequest,
    UserDetail,
    UserListResponse,
)
from app.schemas.alert import (
    AcknowledgeAlertRequest,
    AcknowledgeAlertResponse,
    AlertAcknowledgeRequest,
    AlertDetail,
    AlertListResponse,
    RedFlagAlertResponse,
    RedFlagRuleCreate,
    RedFlagRuleDetail,
    RedFlagRuleListResponse,
    RedFlagRuleResponse,
    RedFlagRuleUpdate,
)
from app.schemas.audit_log import AuditLogDetail
from app.schemas.auth import (
    ChangePasswordRequest,
    ForgotPasswordRequest,
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    MessageResponse,
    RefreshRequest,
    RefreshResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterRequest,
    ResetPasswordRequest,
    UserInfo,
)
from app.schemas.common import (
    CursorPagination,
    ErrorDetail,
    ErrorResponse,
    HealthResponse,
    PaginatedResponse,
    SuccessResponse,
)
from app.schemas.complaint import (
    ComplaintCreate,
    ComplaintDetail,
    ComplaintListResponse,
    ComplaintReorderRequest,
    ComplaintResponse,
    ComplaintUpdate,
    ReorderRequest,
    ReorderResponse,
)
from app.schemas.conversation import ConversationCreate, ConversationResponse
from app.schemas.dashboard import (
    DashboardStatsResponse,
    PatientQueueResponse,
    QueueItemResponse,
    QueueResponse,
    RecentAlertsResponse,
    RecentSessionsResponse,
)
from app.schemas.notification import (
    FCMTokenCreate,
    FCMTokenResponse,
    MarkAllReadResponse,
    MarkReadResponse,
    NotificationListResponse,
    NotificationResponse,
    UnreadCountResponse,
)
from app.schemas.patient import (
    PatientCreate,
    PatientDetail,
    PatientListResponse,
    PatientResponse,
    PatientUpdate,
)
from app.schemas.report import (
    GenerateReportRequest,
    GenerateReportResponse,
    ReportDetail,
    ReportListResponse,
    ReviewReportRequest,
    ReviewReportResponse,
    ReviewRequest,
    SOAPReportDetailResponse,
    SOAPReportResponse,
)
from app.schemas.ws_message import WSMessage, WSSeverity, send_ws_message
from app.schemas.session import (
    ConversationListResponse,
    SessionAssignRequest,
    SessionCreate,
    SessionDetail,
    SessionDetailResponse,
    SessionListResponse,
    SessionResponse,
    SessionStatusResponse,
    SessionStatusUpdate,
    SessionUpdateStatus,
)

__all__ = [
    # Common
    "CursorPagination",
    "PaginatedResponse",
    "ErrorDetail",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",
    # Auth
    "LoginRequest",
    "LoginResponse",
    "RegisterRequest",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "RefreshRequest",
    "RefreshResponse",
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "LogoutRequest",
    "MessageResponse",
    "UserInfo",
    # Patient
    "PatientCreate",
    "PatientUpdate",
    "PatientResponse",
    "PatientDetail",
    "PatientListResponse",
    # Session
    "SessionCreate",
    "SessionResponse",
    "SessionDetailResponse",
    "SessionDetail",
    "SessionUpdateStatus",
    "SessionStatusUpdate",
    "SessionStatusResponse",
    "SessionAssignRequest",
    "SessionListResponse",
    "ConversationListResponse",
    # Conversation
    "ConversationCreate",
    "ConversationResponse",
    # Complaint
    "ComplaintCreate",
    "ComplaintUpdate",
    "ComplaintResponse",
    "ComplaintDetail",
    "ComplaintListResponse",
    "ComplaintReorderRequest",
    "ReorderRequest",
    "ReorderResponse",
    # Report
    "SOAPReportResponse",
    "SOAPReportDetailResponse",
    "ReportDetail",
    "ReportListResponse",
    "ReviewRequest",
    "ReviewReportRequest",
    "ReviewReportResponse",
    "GenerateReportRequest",
    "GenerateReportResponse",
    # Alert
    "RedFlagAlertResponse",
    "AlertAcknowledgeRequest",
    "AcknowledgeAlertRequest",
    "AcknowledgeAlertResponse",
    "AlertDetail",
    "AlertListResponse",
    "RedFlagRuleCreate",
    "RedFlagRuleUpdate",
    "RedFlagRuleResponse",
    "RedFlagRuleDetail",
    "RedFlagRuleListResponse",
    # Dashboard
    "DashboardStatsResponse",
    "QueueItemResponse",
    "QueueResponse",
    "PatientQueueResponse",
    "RecentSessionsResponse",
    "RecentAlertsResponse",
    # Notification
    "NotificationResponse",
    "NotificationListResponse",
    "UnreadCountResponse",
    "MarkReadResponse",
    "MarkAllReadResponse",
    "FCMTokenCreate",
    "FCMTokenResponse",
    # Admin
    "AdminUserCreate",
    "AdminUserUpdate",
    "AdminUserResponse",
    "AdminUserListResponse",
    "CreateUserRequest",
    "UpdateUserRequest",
    "UserDetail",
    "UserListResponse",
    "SystemHealthResponse",
    "ToggleActiveResponse",
    "AuditLogResponse",
    "AuditLogListResponse",
    "AuditLogDetail",
    # WebSocket canonical message
    "WSMessage",
    "WSSeverity",
    "send_ws_message",
]
